// default package
// Generated 2016-11-27 13:36:33 by Hibernate Tools 4.3.1.Final
package com.ustc.domain;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dividefileinfo generated by hbm2java
 */
/*@Entity
@Table(name = "dividefileinfo", catalog = "test_02")*/
@SuppressWarnings(value = { "serial" })
public class Dividefileinfo implements java.io.Serializable {

	private Integer divFileId;
	private Uploadfileinfo uploadfileinfo;
	private String pptFileName;
	private Integer pptPageNumber;
	private String fileName;
	private String fileUrl;
	private String createBy;
	private Date createTime;
	private SinglePagePptItem singlepagepptitems ;

	/*@Id
	@Column(name = "divFile_id", unique = true, nullable = false, length = 50)*/
	public Integer getDivFileId() {
		return this.divFileId;
	}

	public void setDivFileId(Integer divFileId) {
		this.divFileId = divFileId;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "file_id")*/
	public Uploadfileinfo getUploadfileinfo() {
		return this.uploadfileinfo;
	}

	public void setUploadfileinfo(Uploadfileinfo uploadfileinfo) {
		this.uploadfileinfo = uploadfileinfo;
	}

	//@Column(name = "pptFileName", length = 100)
	public String getPptFileName() {
		return this.pptFileName;
	}

	public void setPptFileName(String pptFileName) {
		this.pptFileName = pptFileName;
	}

	//@Column(name = "pptPageNumber")
	public Integer getPptPageNumber() {
		return this.pptPageNumber;
	}

	public void setPptPageNumber(Integer pptPageNumber) {
		this.pptPageNumber = pptPageNumber;
	}

	//@Column(name = "fileName", length = 100)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

//	@Column(name = "fileUrl", length = 100)
	public String getFileUrl() {
		return this.fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	/*@Column(name = "createBy", length = 50)*/
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/*@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)*/
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "dividefileinfo")*/
	public SinglePagePptItem getSinglepagepptitems() {
		return this.singlepagepptitems;
	}

	public void setSinglepagepptitems(SinglePagePptItem singlepagepptitems) {
		this.singlepagepptitems = singlepagepptitems;
	}

}
