package com.ustc.domain;
// Generated 2016-11-27 13:36:33 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;


/**
 * User generated by hbm2java
 */
/*@Entity
@Table(name = "user", catalog = "test_02")*/
public class User implements java.io.Serializable {

	private Integer userId;	
	private String token;
	private String userName;
	private Integer genter;	
	private String email;
	private String mobile;
	private String picUrl;
	private String activeId;
	private String password;
	private Date createTime;
	private Date updateTime;
	private Set<Uploadfileinfo> uploadfileinfos ;//= new HashSet<Uploadfileinfo>();
	private Set<SinglePagePptItem> singlePagePptItem; //=new HashSet<SinglePagePptItem>();
	//private Set<UserPptitem> userPptitems = new HashSet<UserPptitem>();

    
	public Set<SinglePagePptItem> getSinglePagePptItem() {
		return singlePagePptItem;
	}

	public void setSinglePagePptItem(Set<SinglePagePptItem> singlePagePptItem) {
		this.singlePagePptItem = singlePagePptItem;
	}

	/*@Id
	@Column(name = "user_id", unique = true, nullable = false, length = 50)*/
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	
	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	/*@Column(name = "userName", nullable = false, length = 50)*/
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	public Integer getGenter() {
		return genter;
	}

	public void setGenter(Integer genter) {
		this.genter = genter;
	}


	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "picUrl", length = 100)
	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	@Column(name = "activeId", length = 64)
	public String getActiveId() {
		return this.activeId;
	}

	public void setActiveId(String activeId) {
		this.activeId = activeId;
	}

	/*@Column(name = "PASSWORD", nullable = false, length = 50)*/
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	/*@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)*/
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/*@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)*/
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")*/
	public Set<Uploadfileinfo> getUploadfileinfos() {
		return this.uploadfileinfos;
	}

	public void setUploadfileinfos(Set<Uploadfileinfo> uploadfileinfos) {
		this.uploadfileinfos = uploadfileinfos;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")*/
	/*public Set<UserPptitem> getUserPptitems() {
		return this.userPptitems;
	}

	public void setUserPptitems(Set<UserPptitem> userPptitems) {
		this.userPptitems = userPptitems;
	}*/

}
