package com.ustc.domain;
// default package
// Generated 2016-11-8 20:05:56 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "test_01")
public class User01 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String uid;
	private String uname;
	private String upassword;
	private String uphone;
	private String umail;
	private Date createtime;
	private Date updatetime;

	public User01() {
	}

	public User01(String uid, String uname, String upassword) {
		this.uid = uid;
		this.uname = uname;
		this.upassword = upassword;
	}

	public User01(String uid, String uname, String upassword, String uphone, String umail, Date createtime,
			Date updatetime) {
		this.uid = uid;
		this.uname = uname;
		this.upassword = upassword;
		this.uphone = uphone;
		this.umail = umail;
		this.createtime = createtime;
		this.updatetime = updatetime;
	}

	@Id
	@GenericGenerator(name="uuid",strategy="uuid")
	@GeneratedValue(generator ="uuid")
	@Column(name = "uid", unique = true, nullable = false, length = 50)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "uname", nullable = false, length = 50)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "upassword", nullable = false, length = 32)
	public String getUpassword() {
		return this.upassword;
	}

	public void setUpassword(String upassword) {
		this.upassword = upassword;
	}

	@Column(name = "uphone", length = 20)
	public String getUphone() {
		return this.uphone;
	}

	public void setUphone(String uphone) {
		this.uphone = uphone;
	}

	@Column(name = "umail", length = 32)
	public String getUmail() {
		return this.umail;
	}

	public void setUmail(String umail) {
		this.umail = umail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

}
